title: MatSimPy
description: Using Python for Materials Science
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: C. Reimer
repo_url: "https://github.com/CLEANit/MatSimPy"
edit_on_github: true
github_docs_folder: true
include_homepage_in_sidebar: false
logo: 'https://github.com/CLEANit/MatSimPy/blob/main/docs/assets/images/MatSimPy_logo.png'
#site_favicon: 'https://your.url/here.ico'
sticky_navigation: true
search_enabled: true
google_analytics_anonymize_ip: true
hljs_style: github-gist
prev_next_buttons_location: Bottom
